const ADD_UNGUESSED_LETTER = 'ADD_UNGUESSED_LETTER';
const ADD_GUESSED_LETTER = 'ADD_GUESSED_LETTER';
const RESET_KEYBOARD = 'RESET_KEYBOARD';

export { ADD_GUESSED_LETTER, ADD_UNGUESSED_LETTER, RESET_KEYBOARD };
